//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontLibBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontLibBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FontLibBuilder: 嵌入式字体库生成器。
        ///自动为嵌入式应用生成字体库。会在源码中自动寻找字符串，并为之生成字体库。可选按照模板生成文件。
        ///用法：
        ///	FontLibBuilder 
        ///		{ -i &lt;Files&gt; | -d &lt;Directories&gt; -e &lt;Extensions&gt; [-r] } 
        ///		-tmpl &lt;Template File&gt;
        ///		-o &lt;Output File&gt;
        ///		-s &lt;FontSize&gt;
        ///		[--noindex]
        ///		[--encoding &lt;Encoding&gt;]
        ///		[--font &lt;Font&gt;]
        ///
        ///解释：
        ///	-i: 输入文件名。可以为多个文件，例如 -i file1.cpp 或 -i file1.cpp file2.cpp。
        ///	-d：输入目录名。可以为多个目录。
        ///	-e: 要查找的文件扩展名。可以为多种扩展名。
        ///	-r: 递归遍历子文件夹。
        ///	-tmpl: 指定输出模板文件。
        ///		模板输出占位符：
        ///			Data: 以十六进制数输出的字库数据，例如 0001AB。
        ///			DataArray: 以 C 风格输出的字库数据，例如 0x [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
